# Generated by Django 4.2.2 on 2023-07-06 20:23

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_modeltestrandomfield_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', app1.models.MyCustomField(max_length=100, null=True)),
            ],
        ),
    ]
